config/routes.rb
Rails.application.routes.draw do
  resources :organizations do
  	resources :people
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   root to: 'organizations#index', as: 'organizations_index'
  # login

  get '/login', to: 'auth#form_login', as: 'form_login'
  post '/login', to: 'auth#login', as: 'login_post'

  get '/search', to: 'organizations#search', as: 'organizations_search'

  # logout
  delete '/logout/:id', to: 'auth#logout', as: 'user_logout'
end

app/models/person.rb
class Person < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
	validates :name, presence: true
    validates :phone, presence: true, uniqueness: true, numericality: true
    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :avatar, presence: true

    belongs_to :organization

    def self.search(search)
    	where("lower(name) LIKE :search", search: "%#{search.downcase}%").uniq
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :user_signed_in?
  before_action :set_person, only: %i[ show edit update destroy ]
  helper_method :current_user

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to organization_path(@person.organization_id), notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to organization_path(@person.organization_id), notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to organization_path(@person.organization_id), notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:name, :phone, :email, :avatar, :organization_id)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_area :name,class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :avatar %>
    <%= form.text_area :avatar, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<div class="container p-3 my-3 border">	
	<h1>Editing Person</h1>

	<%= form_with(model: @person, url: organization_person_path(params[:organization_id])) do |form| %>
		  <% if @person.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

		      <ul>
		        <% @person.errors.each do |error| %>
		          <li><%= error.full_message %></li>
		        <% end %>
		      </ul>
		    </div>
		  <% end %>

		  <div class="field form-group">
		    <%= form.label :name %>
		    <%= form.text_field :name,class: "form-control" %>
		  </div>

		  <div class="field form-group">
		    <%= form.label :phone %>
		    <%= form.text_field :phone, class: "form-control" %>
		  </div>

		  <div class="field form-group">
		    <%= form.label :email %>
		    <%= form.text_field :email, class: "form-control" %>
		  </div>

		  <div class="field form-group">
		    <%= form.label :avatar %>
		    <%= form.file_field :avatar, class: "form-control" %>
		  </div>

		  <div class="actions">
		    <%= form.submit %>
		  </div>
		<% end %>

	<%= link_to 'Show', organization_person_path(params[:organization_id],@person) %> |
	<%= link_to 'Back', organization_path(params[:organization_id]) %>
</div>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.phone %></td>
        <td><%= person.email %></td>
        <td><%= person.avatar %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/people/new.html.erb
<div class="container p-3 my-3 border">
	<h1>New Person</h1>

	<%= form_with(model: @person, url: organization_people_path, html: { multipart: true }) do |form| %>
	  <% if @person.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

	      <ul>
	        <% @person.errors.each do |error| %>
	          <li><%= error.full_message %></li>
	        <% end %>
	      </ul>
	    </div>
	  <% end %>

	  <%= form.hidden_field(:organization_id, :value => params[:organization_id]) %>

	  <div class="field form-group">
	    <%= form.label :name %>
	    <%= form.text_field :name,class: "form-control" %>
	  </div>

	  <div class="field form-group">
	    <%= form.label :phone %>
	    <%= form.text_field :phone, class: "form-control" %>
	  </div>

	  <div class="field form-group">
	    <%= form.label :email %>
	    <%= form.text_field :email, class: "form-control" %>
	  </div>

	  <div class="field form-group">
	    <%= form.label :avatar %>
	    <%= form.file_field :avatar, class: "form-control" %>
	  </div>

	  <div class="actions">
	    <%= form.submit %>
	  </div>
	<% end %>


	<%= link_to 'Back', organization_path(params[:organization_id]) %>

app/views/people/show.html.erb
<div class="container p-3 my-3 border" style="margin-top: 30px;">
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Name:</strong>
	  <%= @person.name %>
	</p>

	<p>
	  <strong>Phone:</strong>
	  <%= @person.phone %>
	</p>

	<p>
	  <strong>Email:</strong>
	  <%= @person.email %>
	</p>

	<p>
	  <strong>Avatar:</strong>
	  <%= @person.avatar %>
	</p>

	<%= link_to 'Edit', edit_organization_person_path(params[:organization_id],@person), class: "btn btn-warning" %>
	<%= link_to 'Back', organization_path(params[:organization_id]), class: "btn btn-default" %>
</div>