config/routes.rb
Rails.application.routes.draw do
  resources :organizations do
  	resources :people
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   root to: 'organizations#index', as: 'organizations_index'
  # login

  get '/login', to: 'auth#form_login', as: 'form_login'
  post '/login', to: 'auth#login', as: 'login_post'

  get '/search', to: 'organizations#search', as: 'organizations_search'

  # logout
  delete '/logout/:id', to: 'auth#logout', as: 'user_logout'
end

app/models/organization.rb
class Organization < ApplicationRecord
	mount_uploader :logo, LogoUploader
	validates :name, presence: true
    validates :phone, presence: true, uniqueness: true, numericality: true
    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :website, presence: true
    validates :logo, presence: true
    validates :user_id, presence: true

    has_many :persons
    belongs_to :user, foreign_key: :user_id, optional: true


    scope :search, -> (search) {
	    where('organizations.name like :q OR people.name like :q', q: "%#{search}%") if search.present?
	  }
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  before_action :user_signed_in?
  before_action :set_organization, only: %i[ show edit update destroy ]
  helper_method :current_user

  # GET /organizations or /organizations.json
  def index
    if session[:role_id] == 1
     @organizations = Organization.all
    else
      @organizations = Organization.where(user_id: session[:user_id])
      @organizations_noaccess = Organization.where.not(user_id: session[:user_id])
    end
  end

  # GET /organizations/1 or /organizations/1.json
  def show
    @persons = Person.where(organization_id: params[:id])
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
    @users = User.all
  end

  # GET /organizations/1/edit
  def edit
    @users = User.all
  end

  # POST /organizations or /organizations.json
  def create
    @users = User.all
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: "Organization was successfully created." }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1 or /organizations/1.json
  def update
    @users = User.all
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: "Organization was successfully updated." }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1 or /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: "Organization was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    if params[:search].blank?
      redirect_to organizations_path and return
    else
      @parameter = params[:search].downcase
      # @results = Organization.all.where("lower(name) LIKE :search", search: "%#{@parameter}")
      # @matchOrganizations = Organization.where("name LIKE ?", "%#{@parameter}%")
      # @matchPerson = Person.search("%#{@parameter}")
      @organizations = Organization.includes(:persons).references(:persons).search(params[:search])
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organization_params
      params.require(:organization).permit(:name, :phone, :email, :website, :logo, :user_id)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_with(model: organization) do |form| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
        <% organization.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :website %>
    <%= form.text_field :website, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :logo %>
    <%= form.file_field :logo, class: "form-control" %>
  </div>

  <%= form.label :Account %>
    <%= form.select(:user_id) do %>
      <%= content_tag(:option, "Pilih Account", value: 0) %>
      <% @users.each do |u| -%>
        <%= content_tag(:option, u.name, value: u.id) %>
      <% end %>
    <% end %>

  <div class="actions">
    <%= form.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<div class="container p-3 my-3 border">

	<h1>Editing Organization</h1>

	<%= render 'form', organization: @organization %>

	<%= link_to 'Show', @organization, class: "btn btn-success" %> |
	<%= link_to 'Back', organizations_path, class: "btn btn-default" %>
</div>

app/views/organizations/index.html.erb
<div class="container p-3 my-3 border">
    <%= form_tag(organizations_search_path, :method => "get") do %>
      <div class="input-group">
        <%= search_field_tag :search, params[:search], placeholder: "Type ", class: "form_control" %>
        <div class="input-group-btn">
          <%= button_tag " Search for Organization", class: "btn btn-info glyphicon glyphicon-search", :name => nil%>
        </div>
      </div>
    <% end %>
  <% if notice %>
    <p id="notice" class="alert alert-success" ><%= notice %></p>
  <% end %>

  <h1>Organizations</h1>
  <%= link_to 'Logout', user_logout_path(current_user), class:"btn btn-danger pull-right", style: "margin-bottom:20px;", method: :delete%>
  <%= link_to 'New Organization', new_organization_path, {class:"btn btn-success", style: "margin-bottom:20px;"} %>
  <table class="table table-stripped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Website</th>
        <th>Logo</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @organizations.each do |organization| %>
        <tr>
          <td><%= organization.name %></td>
          <td><%= organization.phone %></td>
          <td><%= organization.email %></td>
          <td><%= organization.website %></td>
          <td><%= organization.logo %></td>
          <td><%= link_to 'Show', organization, class: "btn btn-primary" %></td>
          <td><%= link_to 'Edit', edit_organization_path(organization), class: "btn btn-warning" %></td>
          <td><%= link_to 'Destroy', organization, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      <% if @organizations_noaccess %>
        <% @organizations_noaccess.each do |organization| %>
          <tr>
            <td><%= organization.name %></td>
            <td><%= organization.phone %></td>
            <td><%= organization.email %></td>
            <td><%= organization.website %></td>
            <td><%= organization.logo %></td>
            <td><%= link_to 'Show', organization, class: "btn btn-primary" %></td>
          </tr>
        <% end %>
      <% end %>

    </tbody>
  </table>

  <br>

  
</div>

app/views/organizations/new.html.erb
<div class="container p-3 my-3 border">
	<h1>New Organization</h1>

	<%= render 'form', organization: @organization %>

	<%= link_to 'Back', organizations_path, class: "btn btn-default" %>
</div>

app/views/organizations/search.html.erb
<h3>Search result</h3>

<% @organizations.each do |organization| %>
	<%= link_to organization.name, organization_path(organization.id) %>
<% end %>

app/views/organizations/show.html.erb
<div class="container p-3 my-3 border">
  <h3>Organization Detail</h3>
  <% if notice %>
    <p id="notice" class="alert alert-success" ><%= notice %></p>
  <% end %>

  <p>
    <strong>Name:</strong>
    <%= @organization.name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= @organization.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @organization.email %>
  </p>

  <p>
    <strong>Website:</strong>
    <%= @organization.website %>
  </p>

  <p>
    <strong>Logo:</strong>
    <%= image_tag @organization.logo.url,  style: 'height:10vw;width:10vw;margin-bottom:20px;'  %>
  </p>
  <p>
    <strong>Account Manager:</strong>
    <%= @organization.user.name %>
  </p>
  <% if session[:user_id] ==  @organization.user_id || session[:user_id] == 1 %>
    <%= link_to 'Edit', edit_organization_path(@organization), class: "btn btn-warning" %> |
  <% end %>
  <%= link_to 'Back', organizations_path, class: "btn btn-default" %>

  <h3>List Person</h3>
   <% if session[:user_id] ==  @organization.user_id || session[:user_id] == 1 %>
    <%= link_to 'Add New Person', new_organization_person_path(@organization), class: "btn btn-success" %>
    <% end %>
  <table class="table table-stripped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @persons.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.phone %></td>
        <td><%= person.email %></td>
        <td><%= image_tag person.avatar.url,  style: 'height:5vw;width:5vw;margin-bottom:20px;' %></td>
        <% if session[:user_id] ==  @organization.user_id || session[:user_id] == 1 %>
          <td><%= link_to 'Show', organization_person_path(@organization,person), class: "btn btn-primary", style: "color:white;" %></td>
          <td><%= link_to 'Edit', edit_organization_person_path(@organization,person), class: "btn btn-warning" %></td>
          <td><%= link_to 'Destroy', organization_person_path(@organization,person), class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

  
 
</div>